image: docker

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  ADAPT_RUN_LONG_TESTS: 1
  ADAPT_TEST_HEAPDUMP: 1

services:
  - name: docker:stable-dind
    command: [ "dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2" ]

before_script:
  - apk update && apk add bash
  - ./bin/dnsmasq
  - |
    if [ "${DOCKER_AUTH_CONFIG}" = "" ]; then
      echo No DOCKER_AUTH_CONFIG CI variable set in Gitlab web UI
      exit 1
    fi
  - . ./bin/setup-docker-auth.sh

test:
  stage: test
  only:
    - branches
    - web
  script:
    - ./bin/make clean
    - ./bin/make build lint coverage
