image: docker

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive
  ADAPT_RUN_LONG_TESTS: 1
  ADAPT_TEST_HEAPDUMP: 1
  # Be explicit about the default Node version for jobs that don't specify
  ADAPT_TEST_NODE_VERSION: "10"
  # This is for certs to be shared between docker client and dind. Must match
  # a volume mount path in gitlab runner's config.toml.
  DOCKER_TLS_CERTDIR: "/certs"
  ADAPT_BUILD_LOGDIR: build/logs
  ADAPT_CI_REPORT: 1

services:
  - name: docker:stable-dind
    command: [ "dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2376", "--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2" ]

stages:
  - test
  - release
  - publish

before_script:
  - mkdir -p "$ADAPT_BUILD_LOGDIR"
  - apk update && apk add bash git moreutils
  - ./bin/dnsmasq
  - |
    if [ "${DOCKER_AUTH_CONFIG}" = "" ]; then
      echo No DOCKER_AUTH_CONFIG CI variable set in Gitlab web UI
      exit 1
    fi
  - . ./bin/setup-docker-auth.sh
  # Resource monitor logging
  - echo "Time     CPU          Rd   Wr  Mem  eth0" > "${ADAPT_BUILD_LOGDIR}/system_resource.log"
  - nohup nmeter "%t %c %b %[mf] %[neth0]" >> "${ADAPT_BUILD_LOGDIR}/system_resource.log" &

.job_common: &job_common
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME-$CI_JOB_ID"
    paths:
      - "$ADAPT_BUILD_LOGDIR"
    when: always
    expire_in: 30 days


test:10:
  <<: *job_common
  stage: test
  only:
    - branches
    - web
    - schedules
  variables:
    ADAPT_TEST_NODE_VERSION: "10"
  script:
    - |
      bash -o pipefail -c './bin/make build check-uncommitted lint web-test coverage \
        |& tee >(ts > "${ADAPT_BUILD_LOGDIR}/test${ADAPT_TEST_NODE_VERSION}_make_output.log")'

test:10.0.0:
  <<: *job_common
  stage: test
  only:
    # Only run when scheduled or manually triggered
    - web
    - schedules
  variables:
    ADAPT_TEST_NODE_VERSION: "10.0.0"
  script:
    - |
      bash -o pipefail -c './bin/make test \
        |& tee >(ts > "${ADAPT_BUILD_LOGDIR}/test${ADAPT_TEST_NODE_VERSION}_make_output.log")'

test:12:
  <<: *job_common
  stage: test
  only:
    # Only run when scheduled or manually triggered
    - web
    - schedules
  variables:
    ADAPT_TEST_NODE_VERSION: "12"
  script:
    - |
      bash -o pipefail -c './bin/make test \
        |& tee >(ts > "${ADAPT_BUILD_LOGDIR}/test${ADAPT_TEST_NODE_VERSION}_make_output.log")'

release:
  <<: *job_common
  stage: release
  only:
    # Only run the release job if:
    # - the pipeline was kicked off manually
    # - ADAPT_RELEASE_TYPE is set (during manual trigger)
    refs:
      - web
    variables:
      - $ADAPT_RELEASE_TYPE
  variables:
    ADAPT_RELEASE_TESTS: 1
  script:
    # Confirm correct setup:
    # - there's a GitLab personal access token in the environment (token must
    #   have write access to the adapt repo)
    # - there's an NPM token in the enviroment (token must have write
    #   access to publish the Adapt packages)
    - |
      if [ -z "${ADAPT_WEB_TOKEN}" ]; then printf "\n\nERROR: ADAPT_WEB_TOKEN must be set\n\n"; exit 1; fi
      if [ -z "${ADAPT_NPM_TOKEN}" ]; then printf "\n\nERROR: ADAPT_NPM_TOKEN must be set\n\n"; exit 1; fi
    - ./scripts/ci/checkout_branch.sh
    - ./bin/make release
  # Don't download log files from previous jobs
  dependencies: []

docs:
  <<: *job_common
  stage: publish
  only:
    refs:
      - master@unboundedsystems/adapt
    # Only run the publish job if there's a personal access token in the
    # environment. The token must have write access to the adapt-web repo.
    variables:
      - $ADAPT_WEB_TOKEN
  script:
    - ./bin/make web-release-master
  # Don't download log files from previous jobs
  dependencies: []
