version: "3.6"
services:
  git-server:
    build: 
      context: ..
    ports: 
      - "12222:22"
    volumes:
      - ./adapt_config:/home/git/config
      - ./adapt-git-server-test-id_rsa.pub:/home/git/.ssh/authorized_keys
  test-client:
    volumes:
      - ./adapt_config:/home/git/config
      - ./ssh_config:/root/.ssh/config
      - ./adapt-git-server-test-id_rsa:/root/.ssh/id_rsa
      - ./test-client:/home/git/test-client
    build:
      context: .
      dockerfile: Dockerfile
  etcd:
    image: quay.io/coreos/etcd
    ports: 
      - 12379:2379
    command: /usr/local/bin/etcd --name etcd --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379
    